import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      },
      colors: {
        background: '#060f15',
        'on-background': '#d3e9f6',
        surface: '#060f15',
        'on-surface': '#d3e9f6',
        'surface-variant': '#132832',
        'on-surface-variant': '#99aebb',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#08151b',
        'surface-container': '#0c1b23',
        'surface-container-high': '#10222a',
        'surface-container-highest': '#132832',
        'surface-bright': '#172f3a',
        'surface-dim': '#060f15',
        primary: {
          DEFAULT: '#faf9fd',
          foreground: '#060f15',
          container: '#eceaee',
          'on-container': '#060f15',
          dim: '#eceaee',
          fixed: '#e3e2e6',
          'on-fixed': '#3e3f42',
          'fixed-dim': '#d5d4d8',
          'on-fixed-variant': '#5b5b5f',
        },
        'on-primary': '#060f15',
        'on-primary-container': '#060f15',
        secondary: {
          DEFAULT: '#bdc8d3',
          foreground: '#060f15',
          container: '#1d272f',
          'on-container': '#9aa5b0',
          dim: '#afbac5',
          fixed: '#e1ecf8',
          'on-fixed': '#3b464f',
          'fixed-dim': '#d3dee9',
          'on-fixed-variant': '#57626c',
        },
        'on-secondary': '#060f15',
        'on-secondary-container': '#060f15',
        tertiary: {
          DEFAULT: '#f5ffc3',
          foreground: '#060f15',
          container: '#e0f583',
          'on-container': '#4f5d00',
          dim: '#d8ec7c',
          fixed: '#e6fb88',
          'on-fixed': '#414d00',
          'fixed-dim': '#d8ec7c',
          'on-fixed-variant': '#5b6b00',
        },
        'on-tertiary': '#060f15',
        'on-tertiary-container': '#060f15',
        error: {
          DEFAULT: '#fd6f85',
          foreground: '#490013',
          container: '#8a1632',
          'on-container': '#ff97a3',
          dim: '#c8475d',
        },
        'on-error': '#ffffff',
        'on-error-container': '#ff97a3',
        outline: '#647884',
        'outline-variant': '#364b55',
        'inverse-surface': '#f4faff',
        'inverse-on-surface': '#4c575d',
        'inverse-primary': '#5e5f62',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
